---

- name: 'Hadoop | Install artifacts'
  block:

    - name: 'Hadoop || Copy and extract archive'
      when: hadoop_home_check.stat.exists == false
      block:

        - name: 'Hadoop ||| Create base root directory at {{ hadoop_home }}'
          file:
            path:   '{{ hadoop_home }}'
            state:  directory

        - name: 'Hadoop ||| Extract archive to {{ hadoop_home }}'
          unarchive:
            src:        '{{ hadoop_dl_artifact_path }}'
            dest:       '{{ hadoop_home }}'
            extra_opts: ['--strip-components=1']
      become: true

    # TODO - set hadoop env variables?
    # TODO - update hadoop alternatives?

