---
- hosts: pi3s
  gather_facts: no
  tasks:
    - name: shutdown
      shell: sleep 2 && /sbin/shutdown -h now
      async: 1
      poll: 0
      become: yes

    - name: wait for system to go down
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped

