---


- name: swish | make sure some useful things are installed
  apt: name={{item}} state=present
  with_items:
    - git
    - tmux
    - vim
    - zsh
  become: true


- name: swish | create account
  user:
    name: swish
    shell: /bin/zsh
    groups: sudo
    password: "{{ swish_password }}"
  become: true


- name: swish | set authorized key
  authorized_key:
    user: swish
    state: present
    key: "{{ lookup('file', '/home/swish/.ssh/id_rsa.pub') }}"
  become: true

